---
- hosts: all
  become: yes
  tasks:
  - name: Installing firewalld, httpd, mariadb-server, php, and php-mysqlnd packages.
    yum:
      name: 
        - firewalld
        - httpd
        - mariadb-server
        - php
        - php-mysqlnd
      state: started
  - name: firewall service
    service: 
      name: firewalld
      state: started
      enabled: true
  - name: accessing httpd
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
  - name: testing php
    get_url: 
      url: http://materials.example.com/labs/playbook-review/index.php
      dest: /var/www/html/index.php

- name: access to webserver
  hosts: localhost
  become: no
  tasks: 
  - name: checking the service running
    uri:
     url:  http://serverb.lab.example.com
     status_code: 200
