---
- hosts: webserver
  become: yes
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: present
    notify : start apache2
  handlers: start apache2
- name: start apache2
  service:  
      name: apache2
      state: started    