---
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu
    apt: 
      name: "{{jdkonubuntu}}"
      state: present 
    when: ansible_os_family=="Debian"
  - name: install java on redhat 
    yum:
     name: "{{jdkonRedHat}}"  
     state: present
    when: ansible_os_family=="RedHat" 

   