---
- hosts: 172.31.42.142
  become: yes
  tasks: 
  - name:  linux command directly
    command: hostname -f   
    register: myresult

  - name: 
    debug:
     msg: "{{myresult}}"

  - name: install git
    apt:
     name: "{{ubuntuwebpack}}"
     state: present
    when: myresult.stderr !=""
  - name: install tree
    apt: 
     name: "{{ubuntuwebpack}}"
     state: present
    when: myresult.stderr=""                                                                