---
- hosts: 172.31.42.142
  become: yes
  tasks:
  - include_tasks: myfiles.yml  
  - name: create a folder
    file:
     path: /home/ubuntu/myfiles
     state: directory
  - name: copy a file
    copy: 
     src: staticsfile
     dest: /home/ubuntu/mycopyfile.txt  
  - name: install apache
    apt:
     name: "{{ubuntuwebpack}}"
     state: present    
  - name: copy dynamic file
    template: 
      src: mydynamicfile.j2                                                     
      dest: /var/www/html/index.html
  - name: download interner file
    get_url: 
      url: https://get.jenkins.io/war-stable/2.361.1/jenkins.war
      dest: /home/ubuntu   

  - name: download g file
    get_url: 
      url: https://chromeenterprise.google/browser/download/?utm_source=adwords&utm_medium=cpc&utm_campaign=2022-H2-chromebrowser-paidmed-paiddisplay-other-chromebrowserent&utm_term=downloadnow-chrome-browser-download&utm_content=GCEJ&brand=GCEJ&gclid=Cj0KCQjw1bqZBhDXARIsANTjCPJceYTzIiUF6ULNrROqcGBE01VXvXKs0tBlJEobWiY6nK3fUApV-w4aAk7ZEALw_wcB&gclsrc=aw.ds           
      dest: /home/ubuntu
    