---
- hosts: 172.31.42.142
  become: yes
  tasks: 
  - name: install tree
    apt: 
      name: tree
      state: present
    tags: mytree  
      

  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywget

  - name: install git
    apt: 
      name: git
      state: present          
    tags: mygit  