---
- hosts: mywebserver
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu
    apt:
     name: apache2
     state: absent
    when: ansible_os_family=="Debian" 
  - name: run 
    service:     
     name: apache2
     state: stopped
    when: ansible_os_family=="Debian"  
  - name: install Redhat
    yum: 
     name: httpd
     state: absent
    when: ansible_os_family=="RedHat"
  - name: run
    service: 
     name: httpd
     state: stopped
    when: ansible_os_family=="RedHat"      

  

