---
- hosts: mywebserver
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian" 
  - name: run ubuntu
    service:     
     name: apache2
     state: started
    when: ansible_os_family=="Debian"  
  - name: install Redhat
    yum: 
     name: "{{webpackonredhat}}"
     state: present
    when: ansible_os_family=="RedHat"
  - name: run Redhat
    service: 
     name: "{{webpackonredhat}}"
     state: started
    when: ansible_os_family=="RedHat"    
  - name: 
    apt: 
     name: tree
     state: present
    when: ansible_os_family=="Debian"   
 
  


  

