---
- hosts: mywebserver
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian" 
  - name: run 
    service:     
     name: apache2
     state: started
    when: ansible_os_family=="Debian"  
  - name: install Redhat
    yum: 
     name: httpd
     state: present
    when: ansible_os_family=="RedHat"
  - name: run
    service: 
     name: httpd
     state: started
    when: ansible_os_family=="RedHat"    
  - name: install tree
    apt:
     name: tree
     state: present       
    when: ansible_os_family=="Debian" 
  - name: run tree
    service: 
     name: tree
     state: started
    when: ansible_os_family=="Debian" 


  

