---
- hosts: mywebserver
  become: yes
  tasks:
  - name: 
    apt:
     name: tree
     state: present
    when: ansible_os_family=="Debian"  
  - name: 
    service: 
     name: tree    
     state: started
    when: ansible_os_family=="Debian" 