---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver  
    apt:  
     name: "{{mywebpackonubuntu}}"
     state: present
    when: ansible_os_family == "Debain"

    

  - name: i want to run webserver
    service: 
     name: "{{mywebpackonubuntu}}"
     state: started   
    when: ansible_os_family == "Debian"

  - name: i want to install redhat webserver
    yum: 
     name: "{{mywebpackonRedHat}}"
     state: present
    when: ansible_os_family == "RedHat" 

  - name: start webserver
    service:    
      name: "{{mywebpackonRedHat}}"
      state: started
    when: ansible_os_family == "RedHat" 
    
  