---
# tasks file for myvhost
- name: installing httpd
  yum: 
   name: httpd
   state: present
- name: start httpd
  service: 
    name: httpd
    state: started
    enabled: yes
- name: install the configured file
  template: 
   src: vhost.conf.j2
   dest: /etc/httpd/conf.d/vhost.conf
   owner: root
   group: root
   mode: 0644
  notify:
   - restart httpd
